# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4d26ce65d27cdf1a274aebeafb13c613a0b07ae2e7fa738b8702550efc9fc03e3c5b4e12db238ace72324aeb2aa5a246574cb808fe8036a3fe86c9a2568c5eb2

test:
  secret_key_base: d7b22a29e97e18a2ba828a47df7595497e877c75dbc3158f141ef474f03a2ed384eb5c1992963cd971062efb7e8afa9d820598f1bb1456f11df4ed4470347799

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
